networks:
  internal:
    driver: bridge

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    container_name: mariadb
    networks:
      - internal
    env_file: db.env
    volumes:
      - ./data/db/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    container_name: myadmin
    networks:
      - internal
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
  api:
    build:
      context: ./api/
      dockerfile: api.Dockerfile
    container_name: api
    ports:
      - 8000:8000
    networks:
      - internal
    depends_on:
      - mariadb
    env_file:
      - api/api.env