@startuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
!theme sunlust

entity User {
   + id: uuid
   login: varchar
   email: varchar
   hashed_password: varchar
   disabled_at: null | datetime
   deleted_at: null | datetime
   created_at: datetime
   last_login_date: null | datetime
   role: enum {ADMIN, USER}
}

entity Article {
   + id: int
   title: varchar
   content: text
   created_at: datetime
   # id_user: uuid
   # id_category: int
}

entity Category {
   + id: int
   label: varchar
}

entity LoginLog {
   + id: int
   date_connexion: datetime
   # id_user: uuid
}

entity CardiacCoherenceExercise {
   + id: int
   name: varchar
   duration_inspiration: float
   duration_apnea: float
   duration_expiration: float
   number_cycles: int
}

entity ExerciseLog {
   + id: int
   date_execution: datetime
   # id_user: uuid
   # exercise_id: int
}

User -down-> Article
User -down-> LoginLog
User -down-> ExerciseLog
Category -down-> Article
CardiacCoherenceExercise -down-> ExerciseLog
@enduml
