"""init

Revision ID: 42a334c92ef4
Revises: 
Create Date: 2025-06-29 04:03:07.791669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42a334c92ef4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_label'), 'category', ['label'], unique=False)
    op.create_table('exercise_coherence_cardiac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_inspiration', sa.Float(), nullable=False),
    sa.Column('duration_apnea', sa.Float(), nullable=False),
    sa.Column('duration_expiration', sa.Float(), nullable=False),
    sa.Column('number_cycles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_execution', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('exercise_coherence_cardiac_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_coherence_cardiac_id'], ['exercise_coherence_cardiac.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_connexion', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    op.drop_table('exercise_log')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('exercise_coherence_cardiac')
    op.drop_index(op.f('ix_category_label'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
