"""create my table

Revision ID: 6cd838ed70f0
Revises: db1281a01a7a
Create Date: 2025-06-22 15:45:07.103937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cd838ed70f0'
down_revision: Union[str, None] = 'db1281a01a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_coherence_cardiac', sa.Column('duration_inspiration', sa.Float(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('duration_apnea', sa.Float(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('duration_expiration', sa.Float(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('number_cycles', sa.Integer(), nullable=False))
    op.drop_column('exercise_coherence_cardiac', 'numberCycles')
    op.drop_column('exercise_coherence_cardiac', 'durationApnea')
    op.drop_column('exercise_coherence_cardiac', 'durationExpiration')
    op.drop_column('exercise_coherence_cardiac', 'durationInspiration')
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'disabled_at')
    op.add_column('exercise_coherence_cardiac', sa.Column('durationInspiration', mysql.FLOAT(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('durationExpiration', mysql.FLOAT(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('durationApnea', mysql.FLOAT(), nullable=False))
    op.add_column('exercise_coherence_cardiac', sa.Column('numberCycles', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('exercise_coherence_cardiac', 'number_cycles')
    op.drop_column('exercise_coherence_cardiac', 'duration_expiration')
    op.drop_column('exercise_coherence_cardiac', 'duration_apnea')
    op.drop_column('exercise_coherence_cardiac', 'duration_inspiration')
    # ### end Alembic commands ###
