"""delete useless fields

Revision ID: 90121a2eae31
Revises: 6cd838ed70f0
Create Date: 2025-06-29 01:54:51.425347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90121a2eae31'
down_revision: Union[str, None] = '6cd838ed70f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_ibfk_1'), 'category', type_='foreignkey')
    op.drop_column('category', 'id_user')
    op.drop_column('category', 'description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('category', sa.Column('id_user', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key(op.f('category_ibfk_1'), 'category', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###
