"""Remove user exercice history

Revision ID: a190ada7e8f1
Revises: 8b4dc49bc31f
Create Date: 2025-06-30 14:10:51.252682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a190ada7e8f1'
down_revision: Union[str, None] = '8b4dc49bc31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_execution', mysql.DATETIME(), nullable=False),
    sa.Column('id_user', mysql.CHAR(length=32), nullable=False),
    sa.Column('exercise_coherence_cardiac_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_coherence_cardiac_id'], ['exercise_coherence_cardiac.id'], name=op.f('exercise_log_ibfk_1')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('exercise_log_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
