"""Rename Some fields
Revision ID: da912f424371
Revises: 90121a2eae31
Create Date: 2025-06-29 03:40:40.591958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da912f424371'
down_revision: Union[str, None] = '90121a2eae31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('content')
    op.alter_column('category', 'label',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_category_label'), 'category', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_label'), table_name='category')
    op.alter_column('category', 'label',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('content',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_user', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], name=op.f('content_ibfk_1')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('content_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('article')
    # ### end Alembic commands ###
