# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: 'Create .env file'
        working-directory: ./api
        run: |
          mv api.env.example api.env
      - name: Run ruff check
        run: |
          ruff check
      - name: Unit tests (pytest)
        working-directory: ./api
        run: |
          pytest tests/unit
      - name: Integration tests (pytest)
        working-directory: ./api
        run: |
          pytest tests/integration